"""add_additional_commands_to_projects

Revision ID: 17d077e9123e
Revises: 6667382f1cfb
Create Date: 2025-12-30 15:50:41.387438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d077e9123e'
down_revision: Union[str, Sequence[str], None] = '6667382f1cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('additional_commands', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'additional_commands')
    # ### end Alembic commands ###
