"""add_llm_sessions_table

Revision ID: 4c6b0046890e
Revises: 17d077e9123e
Create Date: 2025-12-30 18:33:18.279129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6b0046890e'
down_revision: Union[str, Sequence[str], None] = '17d077e9123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('working_dir', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_sessions_name'), 'llm_sessions', ['name'], unique=False)
    op.create_index(op.f('ix_llm_sessions_project_id'), 'llm_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_sessions_run_id'), 'llm_sessions', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_sessions_task_id'), 'llm_sessions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_sessions_task_id'), table_name='llm_sessions')
    op.drop_index(op.f('ix_llm_sessions_run_id'), table_name='llm_sessions')
    op.drop_index(op.f('ix_llm_sessions_project_id'), table_name='llm_sessions')
    op.drop_index(op.f('ix_llm_sessions_name'), table_name='llm_sessions')
    op.drop_table('llm_sessions')
    # ### end Alembic commands ###
