"""Add priority blocked_by run_id to tasks

Revision ID: 5481f073f90f
Revises: b40f07d85850
Create Date: 2025-12-24 13:07:51.420959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5481f073f90f'
down_revision: Union[str, Sequence[str], None] = 'b40f07d85850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('blocked_by', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'run_id')
    op.drop_column('tasks', 'blocked_by')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
