"""add_handoffs_table

Revision ID: 6667382f1cfb
Revises: d2657c9e4cb3
Create Date: 2025-12-30 15:23:06.091393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6667382f1cfb'
down_revision: Union[str, Sequence[str], None] = 'd2657c9e4cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('from_role', sa.String(length=50), nullable=True),
    sa.Column('to_role', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', name='handoffstatus'), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('context_markdown', sa.Text(), nullable=True),
    sa.Column('context_file', sa.Text(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('agent_report_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_report_id'], ['agent_reports.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoffs_project_id'), 'handoffs', ['project_id'], unique=False)
    op.create_index(op.f('ix_handoffs_run_id'), 'handoffs', ['run_id'], unique=False)
    op.create_index(op.f('ix_handoffs_stage'), 'handoffs', ['stage'], unique=False)
    op.create_index(op.f('ix_handoffs_status'), 'handoffs', ['status'], unique=False)
    op.create_index(op.f('ix_handoffs_task_id'), 'handoffs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoffs_task_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_status'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_stage'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_run_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_project_id'), table_name='handoffs')
    op.drop_table('handoffs')
    # ### end Alembic commands ###
