"""create_role_configs_table

Revision ID: 8463ee0cfeb8
Revises: a7cf3d36ca19
Create Date: 2025-12-26 17:02:37.800607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8463ee0cfeb8'
down_revision: Union[str, Sequence[str], None] = 'a7cf3d36ca19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_configs_id'), 'role_configs', ['id'], unique=False)
    op.create_index(op.f('ix_role_configs_role'), 'role_configs', ['role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_configs_role'), table_name='role_configs')
    op.drop_index(op.f('ix_role_configs_id'), table_name='role_configs')
    op.drop_table('role_configs')
    # ### end Alembic commands ###
