"""add_llm_jobs_table

Revision ID: 8b92d4730395
Revises: dae777ad7c5d
Create Date: 2026-01-01 16:42:10.080709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b92d4730395'
down_revision: Union[str, Sequence[str], None] = 'dae777ad7c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=50), nullable=True),
    sa.Column('position_at_creation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['llm_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_jobs_id'), 'llm_jobs', ['id'], unique=False)
    # Custom indexes for efficient queue queries
    op.create_index('ix_llm_jobs_status_priority', 'llm_jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_llm_jobs_project_id', 'llm_jobs', ['project_id'], unique=False)
    op.create_index('ix_llm_jobs_task_id', 'llm_jobs', ['task_id'], unique=False)
    op.create_index('ix_llm_jobs_job_type', 'llm_jobs', ['job_type'], unique=False)
    op.drop_index(op.f('ix_task_requirements_requirement_id'), table_name='task_requirements')
    op.drop_index(op.f('ix_task_requirements_task_id'), table_name='task_requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_requirements_task_id'), 'task_requirements', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_requirements_requirement_id'), 'task_requirements', ['requirement_id'], unique=False)
    op.drop_index('ix_llm_jobs_job_type', table_name='llm_jobs')
    op.drop_index('ix_llm_jobs_task_id', table_name='llm_jobs')
    op.drop_index('ix_llm_jobs_project_id', table_name='llm_jobs')
    op.drop_index('ix_llm_jobs_status_priority', table_name='llm_jobs')
    op.drop_index(op.f('ix_llm_jobs_id'), table_name='llm_jobs')
    op.drop_table('llm_jobs')
    # ### end Alembic commands ###
