"""add project_id to bug_reports

Revision ID: 9eb5bd5ef076
Revises: 018315fe66d3
Create Date: 2025-12-26 12:01:48.529249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb5bd5ef076'
down_revision: Union[str, Sequence[str], None] = '018315fe66d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_reports', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bug_reports', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bug_reports', type_='foreignkey')
    op.drop_column('bug_reports', 'project_id')
    # ### end Alembic commands ###
