"""add_deployment_history_and_env_commands

Revision ID: be92842b6bc3
Revises: e308585c3055
Create Date: 2025-12-27 16:17:18.533237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be92842b6bc3'
down_revision: Union[str, Sequence[str], None] = 'e308585c3055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('previous_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), nullable=True),
    sa.Column('deploy_command_used', sa.Text(), nullable=True),
    sa.Column('deploy_output', sa.Text(), nullable=True),
    sa.Column('health_check_passed', sa.Boolean(), nullable=True),
    sa.Column('health_check_response', sa.JSON(), nullable=True),
    sa.Column('health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_command_used', sa.Text(), nullable=True),
    sa.Column('test_passed', sa.Boolean(), nullable=True),
    sa.Column('test_output', sa.Text(), nullable=True),
    sa.Column('test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), nullable=True),
    sa.Column('rolled_back_from_id', sa.Integer(), nullable=True),
    sa.Column('rolled_back_to_id', sa.Integer(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['rolled_back_from_id'], ['deployment_history.id'], ),
    sa.ForeignKeyConstraint(['rolled_back_to_id'], ['deployment_history.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_history_environment_id'), 'deployment_history', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployment_history_id'), 'deployment_history', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_history_run_id'), 'deployment_history', ['run_id'], unique=False)
    op.add_column('environments', sa.Column('test_command', sa.Text(), nullable=True))
    op.add_column('environments', sa.Column('rollback_command', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'rollback_command')
    op.drop_column('environments', 'test_command')
    op.drop_index(op.f('ix_deployment_history_run_id'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_id'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_environment_id'), table_name='deployment_history')
    op.drop_table('deployment_history')
    # ### end Alembic commands ###
