"""add_falsification_framework_models

Revision ID: ce7fde9bf3e1
Revises: 8cbd6c502304
Create Date: 2026-01-01 08:26:38.513238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7fde9bf3e1'
down_revision: Union[str, Sequence[str], None] = '8cbd6c502304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('claim_text', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'TASK', name='claimscope'), nullable=True),
    sa.Column('category', sa.Enum('ACCURACY', 'PERFORMANCE', 'SECURITY', 'RELIABILITY', 'USABILITY', 'COMPATIBILITY', 'OTHER', name='claimcategory'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATED', 'FALSIFIED', 'SKIPPED', 'INCONCLUSIVE', name='claimstatus'), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_project_id'), 'claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_claims_task_id'), 'claims', ['task_id'], unique=False)
    op.create_table('claim_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.Enum('GOLD_SET', 'BENCHMARK', 'UNIT_TEST', 'METRIC_THRESHOLD', 'SCRIPT', 'MANUAL_CHECK', name='testtype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('run_on_stages', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', 'SKIPPED', name='teststatus'), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_tests_claim_id'), 'claim_tests', ['claim_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.Enum('METRICS_JSON', 'DIFF_LOG', 'TEST_OUTPUT', 'CSV_REPORT', 'SCREENSHOT', 'LOG_FILE', 'OTHER', name='evidencetype'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('failures', sa.JSON(), nullable=True),
    sa.Column('supports_claim', sa.Boolean(), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['claim_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_run_id'), 'claim_evidence', ['run_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_test_id'), 'claim_evidence', ['test_id'], unique=False)
    op.add_column('projects', sa.Column('require_claims', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('require_evidence_for_gates', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('gold_set_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gold_set_path')
    op.drop_column('projects', 'require_evidence_for_gates')
    op.drop_column('projects', 'require_claims')
    op.drop_index(op.f('ix_claim_evidence_test_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_run_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_claim_tests_claim_id'), table_name='claim_tests')
    op.drop_table('claim_tests')
    op.drop_index(op.f('ix_claims_task_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_project_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
