"""add_proofs_table

Revision ID: d2657c9e4cb3
Revises: 4855779b5576
Create Date: 2025-12-30 14:36:04.549021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2657c9e4cb3'
down_revision: Union[str, Sequence[str], None] = '4855779b5576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('proof_type', sa.Enum('SCREENSHOT', 'LOG', 'REPORT', 'TEST_RESULT', 'CODE_DIFF', 'OTHER', name='prooftype'), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_project_id'), 'proofs', ['project_id'], unique=False)
    op.create_index(op.f('ix_proofs_run_id'), 'proofs', ['run_id'], unique=False)
    op.create_index(op.f('ix_proofs_stage'), 'proofs', ['stage'], unique=False)
    op.create_index(op.f('ix_proofs_task_id'), 'proofs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proofs_task_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_stage'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_run_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_project_id'), table_name='proofs')
    op.drop_table('proofs')
    # ### end Alembic commands ###
