"""add_pipeline_configs_tables

Revision ID: d71bab89c85d
Revises: 157bbc9f206d
Create Date: 2026-01-02 13:09:55.131240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71bab89c85d'
down_revision: Union[str, Sequence[str], None] = '157bbc9f206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('canvas_config', sa.JSON(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_configs_id'), 'pipeline_configs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_configs_project_id'), 'pipeline_configs', ['project_id'], unique=False)
    op.create_table('pipeline_config_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_config_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_config_id'], ['pipeline_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_config_history_id'), 'pipeline_config_history', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_config_history_pipeline_config_id'), 'pipeline_config_history', ['pipeline_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_config_history_pipeline_config_id'), table_name='pipeline_config_history')
    op.drop_index(op.f('ix_pipeline_config_history_id'), table_name='pipeline_config_history')
    op.drop_table('pipeline_config_history')
    op.drop_index(op.f('ix_pipeline_configs_project_id'), table_name='pipeline_configs')
    op.drop_index(op.f('ix_pipeline_configs_id'), table_name='pipeline_configs')
    op.drop_table('pipeline_configs')
    # ### end Alembic commands ###
