"""add raw_output to agent_reports

Revision ID: e308585c3055
Revises: fe9d07dc171f
Create Date: 2025-12-27 13:57:29.631687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e308585c3055'
down_revision: Union[str, Sequence[str], None] = 'fe9d07dc171f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_reports', sa.Column('raw_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_reports', 'raw_output')
    # ### end Alembic commands ###
