"""add_credentials_environments_enhanced_project

Revision ID: e40804b5ea76
Revises: a1b2c3d4e5f6
Create Date: 2025-12-26 01:56:41.355911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e40804b5ea76'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.Enum('API_KEY', 'OAUTH', 'BASIC_AUTH', 'SSH_KEY', 'DATABASE', 'TOKEN', 'CERTIFICATE', 'OTHER', name='credentialtype'), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('token_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=512), nullable=True),
    sa.Column('ssh_key_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_passphrase_encrypted', sa.Text(), nullable=True),
    sa.Column('database_url_encrypted', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_project_id'), 'credentials', ['project_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('env_type', sa.Enum('LOCAL', 'DEVELOPMENT', 'STAGING', 'PRODUCTION', 'TESTING', 'CI_CD', 'OTHER', name='environmenttype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('ssh_host', sa.String(length=255), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(length=255), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=512), nullable=True),
    sa.Column('ssh_key_encrypted', sa.Text(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=True),
    sa.Column('login_url', sa.String(length=512), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('database_host', sa.String(length=255), nullable=True),
    sa.Column('database_port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=255), nullable=True),
    sa.Column('database_url_encrypted', sa.Text(), nullable=True),
    sa.Column('env_vars_encrypted', sa.Text(), nullable=True),
    sa.Column('deploy_command', sa.Text(), nullable=True),
    sa.Column('health_check_url', sa.String(length=512), nullable=True),
    sa.Column('last_deploy_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('repository_url', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('repository_ssh_url', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('primary_branch', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('documentation_url', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('git_credential_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('git_auth_method', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('languages', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('frameworks', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('databases', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('key_files', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('entry_point', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('config_files', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('build_command', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('test_command', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('run_command', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('deploy_command', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('default_port', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('python_version', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('node_version', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'projects', 'credentials', ['git_credential_id'], ['id'])
    # Keep acceptance_criteria - needed for QA workflow
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'is_active')
    op.drop_column('projects', 'node_version')
    op.drop_column('projects', 'python_version')
    op.drop_column('projects', 'default_port')
    op.drop_column('projects', 'deploy_command')
    op.drop_column('projects', 'run_command')
    op.drop_column('projects', 'test_command')
    op.drop_column('projects', 'build_command')
    op.drop_column('projects', 'config_files')
    op.drop_column('projects', 'entry_point')
    op.drop_column('projects', 'key_files')
    op.drop_column('projects', 'databases')
    op.drop_column('projects', 'frameworks')
    op.drop_column('projects', 'languages')
    op.drop_column('projects', 'git_auth_method')
    op.drop_column('projects', 'git_credential_id')
    op.drop_column('projects', 'documentation_url')
    op.drop_column('projects', 'primary_branch')
    op.drop_column('projects', 'repository_ssh_url')
    op.drop_column('projects', 'repository_url')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_credentials_project_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
